version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.2.0
    container_name: housing_mlflow
    command:
      - mlflow
      - server
      - --backend-store-uri
      - sqlite:////data/mlflow.db
      - --serve-artifacts
      - --artifacts-destination
      - /data/mlruns
      - --host
      - 0.0.0.0
      - --port
      - "5000"
    ports:
      - "5500:5000"
    volumes:
      - ./mlruns:/data/mlruns
      - ./mlflow.db:/data/mlflow.db
    restart: unless-stopped

  api:
    image: asatipriyanka/housing-api:latest
    # build:
      # context: .
      # dockerfile: docker/Dockerfile
    container_name: housing_api
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - LOG_DIR=/app/logs
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mlflow
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  streamlit:
    build:
      context: .
    # uses same Dockerfile; overridden command below
      dockerfile: docker/Dockerfile
    container_name: housing_streamlit
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    depends_on:
      - api
    ports:
      - "8501:8501"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: housing_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: housing_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus